#!/bin/bash

set -e


################## Configs ##################

# The line below extracts the version from the list of tags in the Tuist repository.
LATEST_VERSION=$(git ls-remote -t --sort=v:refname https://github.com/runtastic/tuist.git | sed -ne '$s/.*tags\/\(.*\)/\1/p')
TUIST_VERSION="3.32.0-runtastic"
INSTALL_DIR="/usr/local/bin"

################## Helpers ##################

shell_join() {
  local arg
  printf "%s" "$1"
  shift
  for arg in "$@"; do
    printf " "
    printf "%s" "${arg// /\ }"
  done
}

ohai() {
  printf "${tty_blue}==>${tty_bold} %s${tty_reset}\n" "$(shell_join "$@")"
}

warn() {
  printf "${tty_red}Warning${tty_reset}: %s\n" "$(chomp "$1")"
}

sudo_if_install_dir_not_writeable() {
  local command="$1"
  if [ -w $INSTALL_DIR ]; then
    bash -c "${command}"
  else
    bash -c "sudo ${command}"
  fi
}

################## Remote Installation Script ##################

ohai "Downloading tuistenv..."
[ -f /tmp/tuistenv.zip ] && rm /tmp/tuistenv.zip
[ -f /tmp/tuistenv ] && rm /tmp/tuistenv
curl -LSsf --output /tmp/tuistenv.zip https://github.com/runtastic/tuist/releases/download/${LATEST_VERSION}/tuistenv.zip


ohai "Downloading tuist..."
[ -f /tmp/tuist.zip ] && rm /tmp/tuist.zip
[ -f /tmp/tuist ] && rm /tmp/tuist
curl -LSsf --output /tmp/tuist.zip https://github.com/runtastic/tuist/releases/download/${LATEST_VERSION}/tuist.zip


ohai "Unzipping tuistenv..."
unzip -o /tmp/tuistenv.zip -d /tmp/tuistenv > /dev/null

ohai "Unzipping tuist..."
unzip -o /tmp/tuist.zip -d /tmp/tuist > /dev/null

ohai "Installing tuistenv & tuist..."

if [[ ! -d $INSTALL_DIR ]]; then
  sudo_if_install_dir_not_writeable "mkdir -p ${INSTALL_DIR}"
fi

if [[ -f "${INSTALL_DIR}/tuist" ]]; then
  sudo_if_install_dir_not_writeable "rm ${INSTALL_DIR}/tuist"
fi

if [[ ! -d "~/.tuist/Versions/${TUIST_VERSION}" ]]; then
  sudo_if_install_dir_not_writeable "mkdir -p ~/.tuist/Versions/${TUIST_VERSION}"
fi

if [[ -f "~/.tuist/Versions/${TUIST_VERSION}" ]]; then
  sudo_if_install_dir_not_writeable "rm ~/.tuist/Versions/${TUIST_VERSION}"
fi

sudo_if_install_dir_not_writeable "mv /tmp/tuistenv/tuistenv \"${INSTALL_DIR}/tuist\""
sudo_if_install_dir_not_writeable "chmod 777 \"${INSTALL_DIR}/tuist\""

sudo_if_install_dir_not_writeable "mv /tmp/tuist/* ~/.tuist/Versions/${TUIST_VERSION}"
sudo_if_install_dir_not_writeable "chmod 777 ~/.tuist/Versions/${TUIST_VERSION}"

rm -rf /tmp/tuistenv
rm /tmp/tuistenv.zip

rm -rf /tmp/tuist
rm /tmp/tuist.zip

ohai "tuistenv & tuist are installed. Try running 'tuist'"
ohai "Check out the documentation at https://docs.tuist.io/"
